query GetExampleList {
  findExamples {
    _id, title, created
  }
}

query GetExample($_id: ID!) {
  findExample(_id: $_id) {
    _id, title, created
  }
}

query GetUsers {
  findUsers {
    _id, role, name
  }
}
